// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyChatIk_D_rRABHB-eCLfdmM_ByNoLLs04',
    appId: '1:1013910603736:web:403bedeb563a0375fa14ad',
    messagingSenderId: '1013910603736',
    projectId: 'fir-notifications-66851',
    authDomain: 'fir-notifications-66851.firebaseapp.com',
    storageBucket: 'fir-notifications-66851.appspot.com',
    measurementId: 'G-QPZEJW82BW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCFxdjnJxf7u1Ivuu12X4MpXUG9s7yYIj4',
    appId: '1:1013910603736:android:c97586a31f220ac9fa14ad',
    messagingSenderId: '1013910603736',
    projectId: 'fir-notifications-66851',
    storageBucket: 'fir-notifications-66851.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB0to_4OQytxsifiu51qdBIDUu8w4Plb8k',
    appId: '1:1013910603736:ios:3880865347d50fd4fa14ad',
    messagingSenderId: '1013910603736',
    projectId: 'fir-notifications-66851',
    storageBucket: 'fir-notifications-66851.appspot.com',
    iosBundleId: 'com.firebasenotificationslearning.firebasenotifications',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB0to_4OQytxsifiu51qdBIDUu8w4Plb8k',
    appId: '1:1013910603736:ios:3880865347d50fd4fa14ad',
    messagingSenderId: '1013910603736',
    projectId: 'fir-notifications-66851',
    storageBucket: 'fir-notifications-66851.appspot.com',
    iosBundleId: 'com.firebasenotificationslearning.firebasenotifications',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyChatIk_D_rRABHB-eCLfdmM_ByNoLLs04',
    appId: '1:1013910603736:web:3421234ec6aad6d0fa14ad',
    messagingSenderId: '1013910603736',
    projectId: 'fir-notifications-66851',
    authDomain: 'fir-notifications-66851.firebaseapp.com',
    storageBucket: 'fir-notifications-66851.appspot.com',
    measurementId: 'G-BVX4TF7HZD',
  );
}
